[project]
name = "uv-init"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Demo User" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
uv-init = "uv_init:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
